# name:  "CI"
# on:
#   pull_request:
#   push:
#     tags:
#       - "v*.*.*"
#     branches:
#       - main
#   workflow_dispatch:
#     inputs:
#       logLevel:
#         description: 'Log level'
#         required: true
#         default: 'warning'
#
# env:
#   ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
#   MAIN_PYTHON_VERSION: '3.12'
#   DOCUMENTATION_CNAME: 'aedt.radar.explorer.toolkit.docs.pyansys.com'
#   LIBRARY_NAME: 'ansys-aedt-toolkits-radar_explorer'
#   LIBRARY_NAMESPACE: 'ansys.aedt.toolkits.radar_explorer'
#   ON_CI: True
#
# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true
#
# permissions: {} # Disable default permissions
#
# jobs:
#
#   #Â Isolated jobs that run on pull-requests
#
#   update-changelog:
#     name: "Update CHANGELOG (on release)"
#     if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write # Needed to create PR for changelog
#       pull-requests: write # Needed to create PR for changelog
#     steps:
#       - uses: ansys/actions/doc-deploy-changelog@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
#         with:
#           token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
#           bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
#           bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
#           use-upper-case: true
#
#
#
# # # =================================================================================================
# # # vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    RUNNING ON SELF-HOSTED RUNNER    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# # # =================================================================================================
#
# # # =================================================================================================
# # # vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv    RUNNING ON SELF-HOSTED RUNNER    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# # # =================================================================================================
#
#   release:
#     name: "Release"
#     if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
#     needs: [build-library, build-application-windows, build-application-linux-debian, update-changelog]
#     runs-on: ubuntu-latest
#     # Specifying a GitHub environment is optional, but strongly encouraged
#     environment: release
#     permissions:
#       id-token: write # Needed for trusted publishing OIDC
#       contents: write # Needed for releasing to GitHub
#     steps:
#       - name: Download the library artifacts from build-library step
#         uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
#         with:
#           name: ${{ env.LIBRARY_NAME }}-artifacts
#           path: ${{ env.LIBRARY_NAME }}-artifacts
#
#       - name: Release to GitHub
#         uses: ansys/actions/release-github@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
#         with:
#           library-name: ${{ env.LIBRARY_NAME }}
#           token: ${{ secrets.GITHUB_TOKEN }}
#           add-artifact-attestation-notes: true
#           generate_release_notes: false
#
#       - name: "Download all artifacts that got generated in the CI/CD"
#         uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
#         with:
#           path: /tmp/artifacts
#
#       - name: List artifacts
#         run: ls -R /tmp/artifacts
#
#       - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
#         with:
#           files: |
#             /tmp/artifacts/Radar-Explorer-Toolkit-Installer-windows/*.exe
#
#       - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
#         with:
#           files: |
#             /tmp/artifacts/Radar-Explorer-Toolkit-Installer-ubuntu_22.04/*.zip
#
#       - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
#         with:
#           files: |
#             /tmp/artifacts/Radar-Explorer-Toolkit-Installer-ubuntu_24.04/*.zip
#
#       - name: "Upload artifacts to PyPI using trusted publisher"
#         uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
#         with:
#           repository-url: "https://upload.pypi.org/legacy/"
#           print-hash: true
#           packages-dir: ${{ env.PACKAGE_NAME }}-artifacts
#           skip-existing: false
#
#   doc-deploy-dev:
#     name: "Deploy development documentation"
#     if: github.event_name == 'push'
#     needs: build-library
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write # Needed to update files on the gh-pages branch
#     steps:
#       - uses: ansys/actions/doc-deploy-dev@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
#         with:
#           cname: ${{ env.DOCUMENTATION_CNAME }}
#           token: ${{ secrets.GITHUB_TOKEN }}
#           bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
#           bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
#
#   doc-deploy-stable:
#     name: "Deploy stable documentation"
#     if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
#     needs: release
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write # Needed to update files on the gh-pages branch
#     steps:
#       - uses: ansys/actions/doc-deploy-stable@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
#         with:
#           cname: ${{ env.DOCUMENTATION_CNAME }}
#           token: ${{ secrets.GITHUB_TOKEN }}
#           bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
#           bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
