name: release
on:
  push:
    tags:
      - "v*.*.*"

env:
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  MAIN_PYTHON_VERSION: '3.12'
  DOCUMENTATION_CNAME: 'aedt.radar.explorer.toolkit.docs.pyansys.com'
  LIBRARY_NAME: 'ansys-aedt-toolkits-radar_explorer'
  LIBRARY_NAMESPACE: 'ansys.aedt.toolkits.radar_explorer'
  ON_CI: True

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {} # Disable default permissions

jobs:

  update-changelog:
    name: "Update changelog"
    if: contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      contents: write # Write new content to the changelog file
      pull-requests: write # Write access to add or remove new tags
    steps:
      - uses: ansys/actions/doc-deploy-changelog@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  vulnerabilities:
    name: "Vulnerabilities"
    runs-on: ubuntu-latest
    needs: changelog-fragment
    permissions:
      contents: read   # Required to read repository content for vulnerability scanning
    steps:
      - uses: ansys/actions/check-vulnerabilities@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          python-package-name: ${{ env.LIBRARY_NAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          dev-mode: ${{ github.ref != 'refs/heads/main' }}
          extra-targets: 'freeze'

  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: vulnerabilities
    steps:

      - uses: ansys/actions/code-style@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false

      - uses: ansys/actions/check-actions-security@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          generate-summary: true
          token: ${{ secrets.GITHUB_TOKEN }}
          auditing-level: 'high'

  doc-style:
    name: "Documentation style"
    runs-on: ubuntu-latest
    needs: vulnerabilities
    permissions:
      contents: read
      pull-requests: read # Needed for vale to access the content to check
    steps:
      - uses: ansys/actions/doc-style@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  doc-build:
    name: "Build documentation"
    runs-on: [ self-hosted, Windows, pyaedt-toolkit ]
    needs: doc-style
    timeout-minutes: 50
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/doc-build@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false
          add-pdf-html-docs-as-assets: true
          check-links: false

  wheelhouse:
    name: "Wheelhouse ${{ matrix.os }} / ${{ matrix.python}} "
    runs-on: ${{ matrix.os }}
    needs: code-style
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os : [windows-latest, ubuntu-latest]
        python: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: ansys/actions/build-wheelhouse@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python }}
          whitelist-license-check: 'fpdf2 PySide6 PySide6_Addons PySide6_Essentials shiboken6'


  build-application-windows:
    name: "Build Windows Application"
    runs-on: windows-latest
    needs: wheelhouse
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install Dependencies
        run: pip install .[freeze]

      - name: Extract version
        run: |
          python installer/extract_version.py

      - name: Freeze application
        run: pyinstaller frozen.spec

      - name: Install NSIS
        run: choco install nsis -y

      - name: Debug build directory
        run: Get-ChildItem -Path build -Recurse | ForEach-Object { $_.FullName }

      - name: Check NSIS version
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\NSIS\makensis.exe" /VERSION

      - name: Run NSIS
        shell: pwsh
        if: always()
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = "Stop"
          if (!(Test-Path -Path "setup.nsi")) {
            Write-Error "setup.nsi not found"
          }
          & "C:\Program Files (x86)\NSIS\makensis.exe" setup.nsi

      - name: List output
        shell: pwsh
        run: Get-ChildItem -Recurse dist

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: Radar-Explorer-Toolkit-Installer-windows
          path: dist/*.exe
          if-no-files-found: error

  build-application-linux-debian:
    strategy:
      matrix:
        os: [ "24.04", "22.04" ]
      fail-fast: false
    name: "Build Application Linux - Ubuntu ${{ matrix.os }}"
    runs-on: ubuntu-${{ matrix.os }}
    needs: wheelhouse
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install Linux Dependencies
        run: |
          sudo apt update
          sudo apt install aptitude -y;
          sudo aptitude install libfontconfig1-dev \
            libfreetype6-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxrender-dev \
            libxcb1-dev \
            libxcb-glx0-dev \
            libxcb-keysyms1-dev \
            libxcb-image0-dev \
            libxcb-shm0-dev \
            libxcb-icccm4-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-shape0-dev \
            libxcb-randr0-dev \
            libxcb-render-util0-dev \
            libxcb-cursor-dev \
            libxcb-util-dev \
            libxcb-xkb-dev \
            libxcb-xinerama0-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            -y
          sudo apt install ruby -y
          sudo gem install fpm

      - name: Install Python Dependencies
        run: pip install .[freeze]

      - name: Extract version
        run: |
          set -e
          python installer/extract_version.py

      - name: Freeze application
        env:
          ADD_PYTHON_BINARIES: true
        run: pyinstaller frozen.spec

      - name: Setup and Copy Linux files for packaging
        run: |
          mkdir -p package/opt
          mkdir -p package/share/applications
          mkdir -p package/share/icons
          cp -r dist/radar_explorer_toolkit package/opt/radar_explorer_toolkit
          cp installer/assets/splash_icon.svg package/share/icons/splash_icon.svg
          cp installer/linux/debian/radar_explorer_toolkit_prebuild.desktop package/share/applications
          find package/opt/radar_explorer_toolkit -type f -exec chmod 644 -- {} +
          find package/opt/radar_explorer_toolkit -type d -exec chmod 755 -- {} +
          find package/share -type f -exec chmod 644 -- {} +
          chmod +x package/opt/radar_explorer_toolkit/radar_explorer_toolkit
          chmod +x package/opt/radar_explorer_toolkit/_internal/assets/uninstaller_ubuntu.sh
          version=v`cat ./installer/VERSION`
          echo "APPLICATION_VERSION=$version" >> $GITHUB_ENV
          set -x  # Debug mode
          fpm -v $version --fpm-options-file installer/linux/debian/fpm-options-debian

      - name: Create zip file
        env:
          OS_NAME: ${{ matrix.os }}
        run: |
          cp installer/linux/debian/installer.sh installer.sh
          cp installer/linux/debian/postInstallScript.sh postInstallScript.sh
          chmod +x installer.sh postInstallScript.sh radar_explorer_toolkit.deb
          version=$(cat ./installer/VERSION)
          os_version_processed="${OS_NAME//./_}"
          zip_name="Radar-Explorer-Toolkit-Installer-ubuntu_${os_version_processed}.zip"
          echo "OS_VERSION_PROCESSED=${os_version_processed}" >> $GITHUB_ENV
          echo "APPLICATION_VERSION=v${version}" >> $GITHUB_ENV
          zip -r $zip_name radar_explorer_toolkit.deb installer.sh postInstallScript.sh

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: Radar-Explorer-Toolkit-Installer-ubuntu_${{ matrix.os }}
          path: Radar-Explorer-Toolkit-Installer-ubuntu_${{ env.OS_VERSION_PROCESSED }}.zip

  tests_windows:
    name: "Windows Tests"
    runs-on: [self-hosted, Windows, pyaedt-toolkit]
    needs: wheelhouse
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Create Python venv
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1

      - name: Install packages for testing
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install --upgrade build wheel
          pip install .[tests]

      - name: Test API
        timeout-minutes: 30
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v -m radar_toolkit_api --cov=ansys.aedt.toolkits.radar_explorer

      - name: Test Domain Transform API
        timeout-minutes: 5
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v -m domain_transforms --cov=ansys.aedt.toolkits.radar_explorer --cov-append

      - name: Test REST API
        timeout-minutes: 15
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v -m rest_api_toolkit --cov=ansys.aedt.toolkits.radar_explorer --cov-append

      - name: Test Visualization
        timeout-minutes: 5
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v -m radar_visualization --cov=ansys.aedt.toolkits.radar_explorer --cov-append

      - name: Test Run Toolkit utils
        timeout-minutes: 15
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v -m run_utils --cov=ansys.aedt.toolkits.radar_explorer --cov-append

      - name: Test UI
        timeout-minutes: 15
        run: |
          .\.venv\Scripts\Activate.ps1
          pytest -v -m ui --cov=ansys.aedt.toolkits.radar_explorer --cov-append

      - name: "Combine coverage files"
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m coverage html -d .cov\total-html
          python -m coverage xml -o .cov\total.xml

      - name: "Upload coverage results"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          path: .cov/total-html
          name: html-total-coverage

      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          name: codecov-tests-linux
          files: .cov/total.xml
          flags: windows_tests

  tests_linux:
    name: "Linux Tests"
    runs-on: [ self-hosted, Linux, pyaedt-toolkit ]
    needs: wheelhouse
    permissions:
      contents: read
    env:
      ANSYSEM_ROOT252: '/usr/ansys_inc/v252/AnsysEM'
      ANS_NODEPCHECK: '1'
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Create Python venv
        run: |
          python -m venv .venv_linux

      - name: Install packages for testing
        run: |
          source .venv_linux/bin/activate
          pip install .[tests]

      - name: Test API
        timeout-minutes: 15
        run: |
          export LD_LIBRARY_PATH=${ANSYSEM_ROOT252}/common/mono/Linux64/lib64:$LD_LIBRARY_PATH
          source .venv_linux/bin/activate
          pytest -v -m radar_toolkit_api


      - name: Test Domain Transform API
        timeout-minutes: 15
        run: |
          export LD_LIBRARY_PATH=${ANSYSEM_ROOT252}/common/mono/Linux64/lib64:$LD_LIBRARY_PATH
          source .venv_linux/bin/activate
          pytest -v -m domain_transforms

      - name: Test REST API
        timeout-minutes: 5
        run: |
          export LD_LIBRARY_PATH=${ANSYSEM_ROOT252}/common/mono/Linux64/lib64:$LD_LIBRARY_PATH
          source .venv_linux/bin/activate
          pytest -v -m rest_api_toolkit

      - name: Test Visualization
        timeout-minutes: 15
        run: |
          export LD_LIBRARY_PATH=${ANSYSEM_ROOT252}/common/mono/Linux64/lib64:$LD_LIBRARY_PATH
          source .venv_linux/bin/activate
          pytest -v -m radar_visualization

      - name: Test Run Toolkit utils
        timeout-minutes: 15
        run: |
          export LD_LIBRARY_PATH=${ANSYSEM_ROOT252}/common/mono/Linux64/lib64:$LD_LIBRARY_PATH
          source .venv_linux/bin/activate
          pytest -v -m run_utils

  build-library:
    name: "Build library artifacts"
    needs: [doc-build, tests_windows, tests_linux, build-application-windows, build-application-linux-debian]
    runs-on: ubuntu-latest
    permissions:
      attestations: write # Required to create and publish package attestations (SLSA provenance)
      contents: read
      id-token: write # Required for OIDC token generation (for provenance signing)
    steps:
      - uses: ansys/actions/build-library@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          attest-provenance: true

  release:
    name: "Release"
    needs: build-library
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # Needed for trusted publishing OIDC
      contents: write # Needed for releasing to GitHub
    steps:
      - name: Download the library artifacts from build-library step
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: ${{ env.LIBRARY_NAME }}-artifacts
          path: ${{ env.LIBRARY_NAME }}-artifacts

      - name: Release to GitHub
        uses: ansys/actions/release-github@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          add-artifact-attestation-notes: true
          generate_release_notes: false

      - name: "Download all artifacts that got generated in the CI/CD"
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: /tmp/artifacts

      - name: List artifacts
        run: ls -R /tmp/artifacts

      - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            /tmp/artifacts/Radar-Explorer-Toolkit-Installer-windows/*.exe

      - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            /tmp/artifacts/Radar-Explorer-Toolkit-Installer-ubuntu_22.04/*.zip

      - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            /tmp/artifacts/Radar-Explorer-Toolkit-Installer-ubuntu_24.04/*.zip

      - name: "Upload artifacts to PyPI using trusted publisher"
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: "https://upload.pypi.org/legacy/"
          print-hash: true
          packages-dir: ${{ env.PACKAGE_NAME }}-artifacts
          skip-existing: false

  doc-deploy-stable:
    name: "Deploy stable documentation"
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to update files on the gh-pages branch
    steps:
      - uses: ansys/actions/doc-deploy-stable@41f86da4c9ead510db9135e428e33df9cc6f92e1 # v10.2.3
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
